default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= Figaro.env.db_user_name%>
  password: <%= Figaro.env.db_password%>
  socket: <%= Figaro.env.socketLocation %>

development:
  <<: *default
  database: db_dev
test:
  database: db_test
production:
  database: db_production