development:
  adapter: mysql2
  encoding: utf8
  database: db_dev
  pool: 5
  username: root
  password: amodzzi15%
  socket: /var/run/mysqld/mysqld.sock
  strict: false
test:
  adapter: mysql2
  encoding: utf8
  database: db_test
  pool: 5
  username: root
  password: amodzzi15%
  socket: /var/run/mysqld/mysqld.sock
  strict: false
production:
  adapter: mysql2
  encoding: utf8
  database: db_production
  pool: 5
  username: root
  password: amodzzi15%
  socket: /var/run/mysqld/mysqld.sock